services:
  keycloak:
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
    image: quay.io/keycloak/keycloak:26.5.4
    ports:
      - 127.0.0.1:8080:8080
