name: vorpal-nightly

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ALTF4LLC_GITHUB_APP_ID }}
          owner: ${{ github.repository_owner }}
          private-key: ${{ secrets.ALTF4LLC_GITHUB_APP_PRIVATE_KEY }}
          repositories: vorpal

      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view nightly > /dev/null 2>&1; then
            gh release delete --cleanup-tag --yes nightly
          fi

      - uses: actions/checkout@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - run: git fetch --tags

      - run: git tag nightly

      - run: git push --tags
